spring.application.name=Pokedex

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
# Define o caminho para acessar o console (ex: localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configuração da URL de conexão
spring.datasource.url=jdbc:h2:mem:pokedexdb
spring.datasource.driverClassName=org.h2.Driver
